### ISSUE TITLE
``tail: cannot open ‘debian/changelog’ for reading: No such file or directory``

### ISSUE THREAD

**Issue by mdeguzis** [lamby/travis.debian.net#11]
Maybe I am doing something that conflicts with your methods, but the script doesn't seem to fire off.

Raw log (Travis CI): 
https://gist.github.com/ProfessorKaos64/d0941ba979a1e6f7492e

My travis ci file: 
https://github.com/ProfessorKaos64/SteamOS-Tools-Packaging/blob/brewmaster/.travis.yml

I am probably wrong, but wouldn't the [syntax](http://serverfault.com/a/226391) of the command in your travis yml example be (note the space after -O):

```
wget -O - http://travis.debian.net/script.sh | sh -
```

**Comment by lamby** [comment]
> I am probably wrong, but wouldn't the syntax of the command in your travis yml example be (note the space after -O):

Alas this isn't the issue. The salient error message is right there:

`tail: cannot open ‘debian/changelog’ for reading: No such file or directory`

Where is your packaging, btw? Pretty sure we can make it work in a subdirectory if that's necessary, let me know.

**Comment by mdeguzis** [comment]
Ok, so my repository there hosts build scripts where I typically fire off a build script itself to do the build. This clones to a temp directory etc, [like so](https://github.com/ProfessorKaos64/SteamOS-Tools-Packaging/blob/brewmaster/ice/build-ice-unstable.sh). If there was a way that I could specify an environment variable to do this, maybe that would be fine. If this kind of setup can't work, I understand. I know see how you target this at github repos that have debian in the root vs. my methods here where I run a build script, then push a debian directory at build time.

Thank you very much for the reply and this great workaround.

I am now testing this against my old [forked repo](https://github.com/ProfessorKaos64) of the same package (more of a stable build).

If I try to run against that, get this (likely since I build with a different command in build-ice-unstable):

```
Removing intermediate container e468182e2b51
Step 11 : CMD gbp buildpackage --git-ignore-branch --git-export-dir=/build --git-builder='debuild -i -I -uc -us -sa'
 ---> Running in 32b359607b7d
 ---> 74a349981925
Removing intermediate container 32b359607b7d
Successfully built 74a349981925
I: Removing Dockerfile
I: Running build
gbp:error: upstream/0.1.0 is not a valid treeish
```

I suppose the end result could be me creating a fork of this and modifying the final command to pull and run my script in the container. Not sure.

**Comment by lamby** [comment]
> This clones to a temp directory etc.

That seems too complicated to encode into an environment variable tbh. You should do the cloning yourself, put yourself right below the `debian` directory and then make the `wget` call.

(Alternatively, move the `debian/` directory into this repo and avoid all the messy cloning nonsense. It's likely to cause other subtle issues anyway..)

**Comment by mdeguzis** [comment]
Because I have to make modifications sometimes to upstream, i'll just have to test this out on repositories I have forked. For the majority of my builds for SteamOS, I try to avoid extra work maintaining my own fork, but I understand what you mean.

**Comment by lamby** [comment]
No worries - I was just checking.

I'm sure you can make this script work, you just need to call it at the right "custom" point :)

**Comment by mdeguzis** [comment]
Yea, if there was a way I can just pass "custom command" clone my packaging repo and run the build script, that would work. testing that now in a fork, in a crude way of course (substituting the final build line).

If you are willing to shoehorn in something that allows a command like this, I will reopen, otherwise I will test a fork and maintain my own if it works.

**Comment by lamby** [comment]
Sorry, I am explaining myself badly. Passing custom commands _to_ the travis.debian.net script is a bad idea and will likely never be implemented. What I am suggesting is that you do all the custom commands (wherever you like) to set everything in the right place and _then_ you make the call to `wget ... travis.debian.net`. Make sense?

**Comment by mdeguzis** [comment]
Ah Ok, I see. Yes, I understand you correctly there. I'll give that a shot.
