### ISSUE TITLE
Please document if a Github/Gitlab Git repo is required and if not, how to trigger Travis CI builds else

### ISSUE THREAD

**Issue by xtaran** [lamby/travis.debian.net#20]
Hi Chris,

thanks for travis.debian.net. This looks great. Found it via the changelog of diffoscope. (Was surprised that it hasn't been announced on debian-devel-announce or in the Misc. Developer News yet.)

You write on travis.debian.net:

>  If you are using GitHub, your package will be built automatically after pushing

But what if not? I'm using Travis CI for quite some upstream projects, but they're all on Github, so I really wonder how else than pushing to Github or Gitlab could trigger a Travis  CI build. Could you add that (and its answer) either as FAQ or elsewhere in the documentation? Maybe it's also worth documenting it (and the existence of travis.debian.net on [Alioth/Git in the Debian Wiki](https://wiki.debian.org/Alioth/Git).

TIA!

**Comment by lamby** [comment]
> (Was surprised that it hasn't been announced on debian-devel-announce or in the Misc. Developer News yet.)

I blogged about it when I created it, thinking the Publicity Team would pick it up if necessary. Feel free to ping them now. Also, it was highly experimental at the time and thus did not suit a `debian-devel-announce` posting.

>  I'm using Travis CI for quite some upstream projects, but they're all on Github

I don't follow this. If you are using Travis and your projects are on Github, there is nothing special whatsoever going on.

> the existence of travis.debian.net on Alioth/Git in the Debian Wiki.

Please file separate issues for different things :) .. or simply add it to the Debian wiki yourself :) Thanks.

**Comment by xtaran** [comment]
Hi Chris,

> > (Was surprised that it hasn't been announced on
> > debian-devel-announce or in the Misc. Developer News yet.)
> 
> I blogged about it when I created it,

Ah, right. I should read more http://planet.debian.org/ again... Found
it, thanks!

> thinking the Publicity Team would pick it up if necessary. Feel free
> to ping them now.

Will do.

> >  I'm using Travis CI for quite some upstream projects, but they're all on Github
> 
> I don't follow this. If you are using Travis and your projects are
> on Github, there is nothing special whatsoever going on.

Yes. But the relevant part is "upstream". I have tons of Debian
packages whose Git repos are solely hosted on Alioth and I do not
intend to put a copy on Github because then I'd have to take care that
the repos stay in sync.

> > the existence of travis.debian.net on Alioth/Git in the Debian Wiki.
> 
> Please file separate issues for different things :) .. or simply add
> it to the Debian wiki yourself :) Thanks.

That was more a thought than an issue. And I already thought about
adding it myself once this issue is resolved, hence no separate issue.
:-)

**Comment by lamby** [comment]
> I have tons of Debian packages whose Git repos are solely hosted on Alioth and I do not intend to put a copy on Github

This seems more of a question of "how to get some not-Github repo on Travis" rather than it being `travis.debian.net`-specific though, no?

**Comment by xtaran** [comment]
Hi Chris,

> > I have tons of Debian packages whose Git repos are solely hosted on Alioth and I do not intend to put a copy on Github
> 
> This seems more of a question of "how to get some not-Github repo on
> Travis" rather than it being `travis.debian.net`-specific though,
> no?

Yes, but to me, http://travis.debian.net/ (especially the first
paragraph) suggests that it would help me to do so.

And the sentence

> If you are using GitHub, your package will be built automatically
> after pushing

implies to me that there is also another way. Otherwise it would have
to read "You need a Github account and host (or mirror) your git
packaging repo there". (Ok, yes, Gitlab.com IIRC also has Travis CI
support, but I'd expect something more debian-specific here.)

**Comment by lamby** [comment]
> implies to me that there is also another way.

Not to me. _If_ you are using Github, X will be automatic. It carries no implication for me, but will remove it as you might not be the only one.

`travis.debian.net` is not really the place to have documentation on how to get a repo onto Travis and/or mirror stuff to Github. If it's on Travis, then the scope of `travis.debian.net` applies - it's not the job of that FAQ to get stuff to that point and will always do a poor job of it.

**Comment by xtaran** [comment]
Thanks for caring!
