### ISSUE TITLE
Please enable git-submodule

### ISSUE THREAD

**Issue by unera** [lamby/travis.debian.net#30]
If a project uses git-submodule then travis.debian.net works incorrectrly: gbp builds incorrect tarball (without submodules).

I think it should add `gbp --git-[no-]submodules` option to gbp's call (But whezy's gbp doesnt have the option).

Also:

It would be nice if a user could define `$TRAVIS_DEBIAN_GBP_ADD_OPTIONS` variable

**Comment by hosiet** [comment]
I just enabled the Travis integration for a (personal) package with git
submodule in it with the help of (forked) shell script from
travis.debian.net.

I can confirm that adding --git-submodules to gbp argument list would work
well under _trusty beta_ platform provided by Travis CI. No idea if it
would work under Ubuntu 12.04.

P.S. Of course the --git-submodules argument is harmless to those repositories that have no git submodule.

Dmitry E. Oboukhov notifications@github.com于2016年10月17日周一 22:40写道：

**Comment by lamby** [comment]
Enjoy.

Also enjoy `TRAVIS_DEBIAN_GIT_BUILDPACKAGE_OPTIONS` option

**Comment by unera** [comment]
Thanks!

**Comment by unera** [comment]
Again:

git-buildpackage works properly if You do git submodule update --init by hand. So may be the script can provide a hook that can be started before `gbp`, or do `git submodule update --init` (may be recursive) for wheezy?

**Comment by lamby** [comment]
I don't have any testcase for this, so I will have to leave this for you, sorry. Should I revert the previous stuff in the meantime?

**Comment by unera** [comment]
Prev stuff works fine with gbp that understand submodule option.
But wheezy problem is still reproducible.

So I think that adding hook before gbp, or adding git submodule update could resolve the problem on wheezy.

**Comment by unera** [comment]
project of fix the case: https://github.com/unera/travis.debian.net/pull/1

**Comment by lamby** [comment]
can't we detect the use of submodules and run init blah if they exist?

**Comment by unera** [comment]
I'm checking the question now

**Comment by unera** [comment]
No :(
my patch doesn't solve the problem on wheezy, too :(

So for wheezy only hook can solve the problem (user can build tar.gz by hand)

**Comment by unera** [comment]
travis.debian uses `gbp --git-export-dir` option, so if we use a hook to make `git submodule update` it will not work: exported dir will not contain submodules.

So there is no way now to build packages with submodules for wheezy using travis.debian.net

:(

**Comment by lamby** [comment]
"now"? 

Dmitry E. Oboukhov wrote:

> travis.debian uses `gbp --git-export-dir` option, so if we use a hook to make `git submodule update` it will not work: exported dir will not contain submodules.
> 
> So there is no way now to build packages with submodules for wheezy using travis.debian.net
> 
> :(
> 
> ## 
> 
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub:
> https://github.com/lamby/travis.debian.net/issues/30#issuecomment-254498443

## 

Chris Lamb
chris-lamb.co.uk / @lolamby

**Comment by unera** [comment]
> now

For building packages with submodules for wheezy we should exclude using `git-export-dir`.

What is the reason to use the option?

**Comment by lamby** [comment]
> What is the reason to use the option?

Deterministic build location. Useful for reproducible blah, and it also feels safer.

How about we split out all the git-buildpackage arguments and — if using wheezy — we don't add git-export-dir? I'd really like to keep `git-export-dir` and don't want to remove it for everything just for the combination of submodules and wheezy. This solution would also be fairly clean and allow subsequent workarounds.
