### ISSUE TITLE
debuild now "requires" lintian

### ISSUE THREAD

**Issue by freeekanayaka** [lamby/travis.debian.net#32]
Not sure if I should file this against devscripts instead, but starting from devscripts 2.16.9 it seems that debuild is not happy anymore if lintian is not installed:

I: Running build
gbp:info: Exporting 'HEAD' to '/build/twisted-tmp'
gbp:info: Moving '/build/twisted-tmp' to '/build/twisted-16.6.0'
 dpkg-buildpackage -rfakeroot -us -uc -i -I -sa --check-command=lintian
dpkg-buildpackage: warning: using a gain-root-command while being root
dpkg-buildpackage: error: check-commmand 'lintian' not found
debuild: fatal error at line 1036:
dpkg-buildpackage -rfakeroot -us -uc -i -I -sa --check-command=lintian failed
gbp:error: 'debuild -i -I -uc -us -sa' failed: it exited with 29

This snippet was taken from:

https://api.travis-ci.org/jobs/179004122/log.txt?deansi=true

I've downloaded the docker debian:sid image and I can confirm that it's indeed the issue, since I could reproduce it.

Note that in version 2.16.9, debuild has been heavily reworked, see:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=789581

and

https://anonscm.debian.org/cgit/collab-maint/devscripts.git/commit/?id=607c5911b44ca61cf352e80397b5707ee23d9eec

I'm actually surprised nobody noticed this yet.

**Comment by lamby** [comment]
We can close this now I think?
