### ISSUE TITLE
Is `dist: trusty` supported?

### ISSUE THREAD

**Issue by szepeviktor** [lamby/travis.debian.net#37]
Is it OK to use this project with `dist: trusty`?

**Comment by lamby** [comment]
I am not an Ubuntu user/developer but more than wiilling to accept patches to support it. How about you just try it and see..?

**Comment by szepeviktor** [comment]
I am not able to build hundreds of packages 😄 

And I have a rejected PR: https://github.com/lamby/travis.debian.net/pull/28/files

**Comment by szepeviktor** [comment]
Current (on Travis) LTS' date: August 7, 2014
Trusty's date: August 4, 2016
BTW 16.04 LTS is not yet available on Travis.

**Comment by lamby** [comment]
> I not able to build hundreds of packages

Don't follow. Just build one, see if it works..?

> rejected PR
PR was rejected for technical reasons about the fix; wasn't it fixed another way..?

And again, I simply don't use Ubuntu so I am just not able to confirim it works or not, rather than saying "go away".

**Comment by szepeviktor** [comment]
Here it is https://travis-ci.org/szepeviktor/dh-make-php/builds/187319603

**Comment by lamby** [comment]
I'm not entirely sure what you are asking me now. Please file separate bugs if you find specific issues, thank you.

**Comment by szepeviktor** [comment]
I am proposing to switch OS release from precise from trusty.
So all packages using travis.debian.net will build on a more modern Ubuntu release.

**Comment by szepeviktor** [comment]
Currently all tests run on an old LTS release: precise.

**Comment by lamby** [comment]
Please make a PR then with the reasons and a patch. I am really quite confused by this thread.
