### ISSUE TITLE
debian/source/options appears to be ignored for autopkgtests

### ISSUE THREAD

**Issue by lamby** [lamby/travis.debian.net#41]
eg. https://travis-ci.org/ReproducibleBuilds/diffoscope

Missing the ``.a`` and ``.o`` files in the autopkgtests for the above (see also https://github.com/ReproducibleBuilds/diffoscope/blob/master/debian/source/options#L1)  so I think it is ignoring debian/source/options but only here (a regular package build doesn't do this).

**Comment by lamby** [comment]
@evgeni Any ideas here? I don't know much about autopkgtests...

**Comment by evgeni** [comment]
That's interesting. I'll see what can be done here.

**Comment by evgeni** [comment]
Ok, so the `.o` and `.a` are missing from the build.
But that does not seem to be an autopkgtest issue.

a simple:

    debcheckout diffoscope
    cd diffoscope
    gbp buildpackage --git-submodules --git-ignore-branch --git-export-dir=/tmp/build --git-builder='debuild -i -I -uc -us -sa'

yields a `/tmp/build/diffoscope_76.tar.xz` that lacks `test1.a` and `test1.o`.

**Comment by evgeni** [comment]
That is because we pass `-I` to debuild.

**Comment by lamby** [comment]
Ohh!

**Comment by lamby** [comment]
I thought ``-I`` was something to do with lintian info levels!

**Comment by lamby** [comment]
♥
