### ISSUE TITLE
fails with "floating" tags

### ISSUE THREAD

**Issue by mapreri** [lamby/travis.debian.net#43]
I'm seeing this failure that I think it's coming from travis.d.n shortcomings in supporting my workflow.
I'll just leave to you to understand the error (which I don't understand by only reading the log — except noticing it seems to be trying to use a non-existent Debian release "78_bpo8+1").

https://travis-ci.org/ReproducibleBuilds/diffoscope/builds/207661465

**Comment by lamby** [comment]
https://travis-ci.org/ReproducibleBuilds/diffoscope/builds/207661465

Detected correctly here.

**Comment by mapreri** [comment]
Yes, thank you for the promptly fix!
