### ISSUE TITLE
Script fails with manifest for debian:debian not found

### ISSUE THREAD

**Issue by vranki** [lamby/travis.debian.net#58]
I've got a debian package with the standard .travis.yml in travis and the build fails:

End of build log:

Sending build context to Docker daemon  175.6kB
Step 1/16 : FROM debian:debian
manifest for debian:debian not found

https://travis-ci.org/vranki/showet/jobs/368203910

**Comment by lamby** [comment]
Wrong link? I see https://api.travis-ci.org/v3/job/368203910/log.txt which does not mention the use of travis.debian.net at all?

**Comment by vranki** [comment]
Yes, sorry. This is the correct link:

https://api.travis-ci.org/v3/job/422458330/log.txt

**Comment by lamby** [comment]
The issue is that we are incorrecty detecting the "distribution" as `debian` instead of unstable/testing, etc.:

```
I: Automatically detecting distribution
I: Building on: debian
I: Using distribution: debian
```

This is due the `debian` branch name being used (which is completely legitimate). One sec...
