### ISSUE TITLE
Do not remove Dockerfile in script

### ISSUE THREAD

**Issue by lunemec** [lamby/travis.debian.net#59]
Hi, I'm trying to get automatic building of my project using travis.debian.net. But I encountered a problem when the script.sh deletes `Dockerfile` at the end:

```
I: Removing Dockerfile
I: Running build
gbp:error: You have uncommitted changes in your source tree:
gbp:error: HEAD detached at 3772138
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
	deleted:    Dockerfile
no changes added to commit (use "git add" and/or "git commit -a")
gbp:error: Use --git-ignore-new to ignore.
The command "wget -O- http://travis.debian.net/script.sh | sh -" exited with 1.
Done. Your build exited with 1.
```

It is this build: https://travis-ci.org/lunemec/nanny/jobs/430509967 (not sure if you can see that).

Here is my `.travis-ci.yml`: https://github.com/lunemec/nanny/blob/travis-test/.travis.yml

How can I fix this? Thank you.

**Comment by lunemec** [comment]
Thank you for that, but it didn't work. @lamby 

https://travis-ci.org/lunemec/nanny/jobs/430689788

Maybe it would be better for your script to create Dockerfile.travis.debian.net filename, and use that. I bet nobody will use that filename compared to everyone using Dockerfile.

Thank you

**Comment by lamby** [comment]
@lunemec Sorry didn't see your comment until now. I don't understand why the call to `git checkout…` does not restore the file for you. Can you investgate?

**Comment by vranki** [comment]
Not 100% sure if this is the same issue but also complains about Dockerfile, 
although Dockerfile is not present in the project:

```
Successfully tagged travis.debian.net/perse:latest
I: Restoring Dockerfile to previous state
error: pathspec 'Dockerfile' did not match any file(s) known to git.
I: Running build
gbp:error: upstream/1.0.4 is not a valid treeish
The command "wget -O- http://travis.debian.net/script.sh | sh -" exited with 1.
```
Full build log: https://travis-ci.org/vranki/perse

Any ideas what's wrong?

**Comment by lamby** [comment]
`gbp:error: upstream/1.0.4 is not a valid treeish` looks like a different error altogether. ie. you are trying to run this travis job against an upstream tag.

**Comment by vranki** [comment]
It's trying to build branch debian. No tags in the project. I have no clue where 'upstream' comes from.

**Comment by lamby** [comment]
Interesting. Anyway, I still think this a separate issue. Please could you file another issue, perhaps referencing this one for context? Thanks in advance.

**Comment by lamby** [comment]
@lunemec Ping on this?

**Comment by lunemec** [comment]
@lamby sorry I didn't get to it, I'll try to test it over christmas.

**Comment by lamby** [comment]
Hi @lunemec Merry Christmas - any chance of having a look? :)

**Comment by lamby** [comment]
Any luck?

**Comment by lunemec** [comment]
@lamby sorry it took so long, but it seems that the `gbp` error happens before the script gets to the `git checkout -- Dockerfile` part.

```
Step 14/14 : CMD gbp buildpackage --git-submodules --git-ignore-branch --git-export-dir=/build -uc -us -sa
Removing intermediate container 16e8b8a6c37f
Successfully built e79ef5d7804c
Successfully tagged travis.debian.net/nanny:latest
I: Restoring Dockerfile to previous state (safe to ignore errors)
I: Running build
gbp:error: You have uncommitted changes in your source tree:
gbp:error: HEAD detached at 3772138
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
	deleted:    Dockerfile
no changes added to commit (use "git add" and/or "git commit -a")
gbp:error: Use --git-ignore-new to ignore.
The command "wget -O- http://travis.debian.net/script.sh | sh -" exited with 1.
Done. Your build exited with 1.
```

**Comment by lamby** [comment]
Do you have the entire build log for that? That looks like a different repo (not perse?).

When I try perse locally on the `debian` branch I see something different:

```
lamby@tinycat:~/git/forks/perse% TRAVIS_BUILD_NUMBER=0 sh ~/git/debian/github/travis.debian.net/script.sh
[…]
Setting up perse-build-deps (1.0.4-1) ...
Processing triggers for libc-bin (2.28-4) ...
Removing intermediate container a9bd59370055
 ---> e576dc75fba2
Step 11/14 : RUN rm -f Dockerfile
 ---> Running in 191cf1c213d9
Removing intermediate container 191cf1c213d9
 ---> 261394e8edb4
Step 12/14 : RUN git checkout .travis.yml || true
 ---> Running in d3b103f00344
Removing intermediate container d3b103f00344
 ---> a98eef8f5a5d
Step 13/14 : RUN mkdir -p /build
 ---> Running in 368df0eddac1
Removing intermediate container 368df0eddac1
 ---> 2884fcd75cce
Step 14/14 : CMD gbp buildpackage --git-submodules --git-ignore-branch --git-export-dir=/build -uc -us -sa
 ---> Running in 88c4d5258002
Removing intermediate container 88c4d5258002
 ---> d4b235f0e825
Successfully built d4b235f0e825
Successfully tagged travis.debian.net/perse:latest
I: Restoring Dockerfile to previous state (safe to ignore errors)
error: pathspec 'Dockerfile' did not match any file(s) known to git
I: Running build
gbp:error: upstream/1.0.4 is not a valid treeish
```

**Comment by lunemec** [comment]
Here: https://api.travis-ci.org/v3/job/430689788/log.txt

**Comment by lamby** [comment]
Thanks. Can we try and keep to the same issue/bug/package? :)  I'm getting a little bit confused between the two... okay, I think I just fixed it :)
