### ISSUE TITLE
Build error gbp:error: upstream/1.0.4 is not a valid treeish

### ISSUE THREAD

**Issue by vranki** [lamby/travis.debian.net#60]
I'm trying to build perse with travis and the build fails. Full log at https://travis-ci.org/vranki/perse
The build is done in debian branch and there are no tags in the project. Not sure where 'upstream' comes from.

.travis.yml:

https://github.com/vranki/perse/blob/debian/.travis.yml

Possibly related to #59 as Dockerfile is mentioned.

**Comment by KaiHa** [comment]
Hello @vranki, `upstream` comes from the default TAG FORMAT. See the option `--git-upstream-tag` in the `git-buildpackage(1)` manpage.

**Comment by lamby** [comment]
Indeed, you don't see to have git-buildpackage setup correctly for this package. Entirely outside of `travis.debian.net` I get:

```
gbp:info: Postexport hook set, delaying tarball creation
gbp:info: Exporting 'HEAD' to '/tmp/buildd/perse-tmp'
gbp:info: Running Postexport hook
gbp:info: Moving '/tmp/buildd/perse-tmp' to '/tmp/buildd/perse-1.0.4'
gbp:warning: Pristine-tar branch "pristine-tar" not found
gbp:info: Creating /tmp/buildd/perse_1.0.4.orig.tar.gz
gbp:error: upstream/1.0.4 is not a valid treeish
```

:)
