### ISSUE TITLE
[question] Can this project be used by upstreams?

### ISSUE THREAD

**Issue by sten0** [lamby/travis.debian.net#62]
Hi @lamby!

Can this project be used by upstreams?  Specifically I've noticed that Elpy's upstream CI doesn't have access to emacs26, because it's stuck on Ubuntu 16.04.  Alternatively I'm considering adding an experimental branch that tracked upstream's master to the salsa project, and then enabling Gitlab CI following @baldurmen's (pollo's) https://veronneau.org/introduction-to-gitlab-ci.html

Cheers,
Nicholas

**Comment by lamby** [comment]
I'm a little lost what you mean with "can be used by upstreams". (As in, for reason would it not work?)

**Comment by sten0** [comment]
Sorry for being unclear, I confess to ignorance.  I'm wondering if travis.debian.net would be an easy way to add Debian next to the Ubuntu CI targets they're already using on their github project.  AFAICT travis.debian.net doesn't run on Debian infrastructure, but I wanted to verify that it was ok to use it for upstream project CI before proposing the idea to them.  eg: the "debian.net" suffix makes me wonder if it's something only for Debian work and not for upstreams.

**Comment by lamby** [comment]
> to add Debian next to the Ubuntu CI targets 

This is the bit I don't quite understand - can you elaborate on what you mean here? If it helps, travis.debian.net is a way of building `.deb` packages from repositories that use the `git-buildpackage` tool.

**Comment by adrelanos** [comment]
Hi @lamby!

I am not a Debian Developer (DD) (or any other official status in Debian). But I am maintaining Debian derivatives, Whonix and Kicksecure. We have a a lot packages.

Can we (upstream, I am considering myself an upstream here by maintaining Debian packages outside of Debian) use https://travis.debian.net or is this an exclusive service for DD's and packages in Debian? If it's possible to sign up for non-DDs too, how?

**Comment by lamby** [comment]
Anybody can use this service; it is not hosted on Debian infrastucture and the builds do run on anything resembling infrastructure under Debian's command or control or whatever. It is merely a shell script that gets run on https://travis-ci.org/. It requires neither permission or setup for or from anyone. Far from being exclusive, if you can find a use for it then please go ahead.

**Comment by adrelanos** [comment]
How would I use this?

It basically starts Debian in a docker container and builds the package
there?

Is there some example repository that is using this?

**Comment by lamby** [comment]
Please see http://travis.debian.net/ - this should contain enough documentation to get started…. :)
