### ISSUE TITLE
missing cowbuilder

### ISSUE THREAD

**Issue by bene42** [lamby/travis.debian.net#63]
Trying to use travis.debian.net for a project end up in:

```
...
Successfully tagged travis.debian.net/libbbmotor:latest
I: Restoring Dockerfile to previous state (safe to ignore errors)
error: pathspec 'Dockerfile' did not match any file(s) known to git.
I: Running build
dh clean  --with autoreconf
   dh_clean
gbp:info: Creating /build/libbbmotor_0.1.1.orig.tar.gz
gbp:info: Exporting 'HEAD' to '/build/libbbmotor-tmp'
gbp:info: Moving '/build/libbbmotor-tmp' to '/build/libbbmotor-0.1.1'
gbp:info: Performing the build
cowbuilder not found; you need to install the cowbuilder package
gbp:error: 'DIST=sid git-pbuilder -uc -us -sa' failed: it exited with 1
The command "wget -O- http://travis.debian.net/script.sh | sh -" exited with 1.
Done. Your build exited with 1.
```

git-pbuilder recommended: cowbuilder | pbuilder | sbuild
But none of these packages are installed.

Did I lost track or this a bug?

**Comment by lamby** [comment]
@bene42 Can you link to your repository? I would suspect that that your repo has been configured to use cowbuilder. If so, I don't think this a good idea that your *repo* dictates the builder (eg. in `debian/gbp.conf`); that should be up to the user. (Whist you are right about the dependencies, I don't unstand the reason you mention `git-pbuilder` here, if that helps too..)

**Comment by bene42** [comment]
repo can be found at  https://github.com/eurovibes/libbbmotor.
I lost track!
Setting "builder = DIST=sid git-pbuilder" in debian/gbp.conf was a poorly choice.
Sorry for the noise.
