### ISSUE TITLE
Build and autopkgtest on multiple architectures

### ISSUE THREAD

**Issue by kiplingw** [lamby/travis.debian.net#64]
Is there a means to have build and autopkgtests performed on multiple architectures? I'd like to test on armhf, amd64, ppc64el, and s390x.

**Comment by lamby** [comment]
This script only supports the build architectures supported by Travis CI - it runs on there so adopts all of its features and limitations.

**Comment by kiplingw** [comment]
Ah I see. Thanks anyways @lamby.

**Comment by kiplingw** [comment]
@lamby, if I were hypothetically able to obtain server hardware for you, like POWER9, that could host all the major Debian architectures, would that be able to help you at all? @pabs3 and I would love to see this problem solved.

**Comment by lamby** [comment]
From a `travis.debian.net` perspective, I'm afraid not, no. We would need Travis CI to directly support these architectures.

**Comment by kiplingw** [comment]
@pabs3, do you think there is any way the `debci` gods would be able to help him?

**Comment by pabs3** [comment]
Unlikely, debci folks are focussed on providing CI services to Debian.

-- 
bye,
pabs

https://bonedaddy.net/pabs3/
