### ISSUE TITLE
Replace http links with https

### ISSUE THREAD

**Issue by emanuelb** [lamby/travis.debian.net#66]
http links in repo:
https://github.com/lamby/travis.debian.net/blob/1e7660ef9663b0aea0e13f3ad45d6318bcd6a599/travis.yml#L8
https://github.com/lamby/travis.debian.net/blob/1e7660ef9663b0aea0e13f3ad45d6318bcd6a599/index.html#L76
https://github.com/lamby/travis.debian.net/blob/1e7660ef9663b0aea0e13f3ad45d6318bcd6a599/index.html#L78
https://github.com/lamby/travis.debian.net/blob/6aca1fbc34603d2080ad886d1c88109458bb65ba/script.sh#L10
https://github.com/lamby/travis.debian.net/blob/6aca1fbc34603d2080ad886d1c88109458bb65ba/script.sh#L28

**Comment by lamby** [comment]
Please re-submit this as a PR and I'll be happy to merge, thanks.

**Comment by emanuelb** [comment]
> Please re-submit this as a PR and I'll be happy to merge, thanks.

Please tag this issue with labels "first good issue", "newbie", or "hacktoberfest" and re-open, which allows other people to submit PR for this trivial change, see reasoning at: https://salsa.debian.org/reproducible-builds/diffoscope/-/issues/210
