### ISSUE TITLE
Use latest tag for koalaman/shellcheck

### ISSUE THREAD

**Issue by emanuelb** [lamby/travis.debian.net#67]
https://github.com/lamby/travis.debian.net/blob/dcaebbc0b037bb2de34bf7cd96918fdc391b6899/.travis.yml#L15

v0.4.7 is old, latest is: v0.7.1, probably better to use `latest` tag to always use the latest version.

**Comment by lamby** [comment]
Please re-submit this as a test PR and I'll be happy to merge it, thanks.

**Comment by emanuelb** [comment]
> Please re-submit this as a test PR and I'll be happy to merge it, thanks.

Please tag this issue with labels "first good issue", "newbie", or "hacktoberfest" and re-open, which allows other people to submit PR for this trivial change, see reasoning at: https://salsa.debian.org/reproducible-builds/diffoscope/-/issues/210
