### ISSUE TITLE
Merge RUN commands in Dockerfile

### ISSUE THREAD

**Issue by emanuelb** [lamby/travis.debian.net#68]
each RUN command will create layer, it's better to merge them (either by `command1 && command2` or by 
```shell
set -ex; \
command; \
command2
```

to avoid creating not-needed layers, below usages of separate RUN commands that can be merged:

https://github.com/lamby/travis.debian.net/blob/6aca1fbc34603d2080ad886d1c88109458bb65ba/script.sh#L297-L298

https://github.com/lamby/travis.debian.net/blob/6aca1fbc34603d2080ad886d1c88109458bb65ba/script.sh#L304-L305

https://github.com/lamby/travis.debian.net/blob/6aca1fbc34603d2080ad886d1c88109458bb65ba/script.sh#L314-L315

https://github.com/lamby/travis.debian.net/blob/6aca1fbc34603d2080ad886d1c88109458bb65ba/script.sh#L330-L331

https://github.com/lamby/travis.debian.net/blob/6aca1fbc34603d2080ad886d1c88109458bb65ba/script.sh#L356-L358

https://github.com/lamby/travis.debian.net/blob/6aca1fbc34603d2080ad886d1c88109458bb65ba/script.sh#L363-L365

https://github.com/lamby/travis.debian.net/blob/6aca1fbc34603d2080ad886d1c88109458bb65ba/script.sh#L377-L378

https://github.com/lamby/travis.debian.net/blob/6aca1fbc34603d2080ad886d1c88109458bb65ba/script.sh#L409-L411

https://github.com/lamby/travis.debian.net/blob/6aca1fbc34603d2080ad886d1c88109458bb65ba/script.sh#L416-L421

**Comment by lamby** [comment]
Please re-submit this as a (tested) PR so we can more effectively see the trade-offs of making these changes and readability, thanks.

**Comment by emanuelb** [comment]
> so we can more effectively see the trade-offs of making these changes and readability, thanks.

If the RUN commands are merged in each above block separately (easy fix) there no trade-off, but better fix would be to merge the commands between blocks (as/if they are written to the same file), so adding logic like
```
if(!already_in_run_command) echo/write "RUN ";
write_commands;
```
and the commands each end with `\` (so next line will be command as well), ending RUN can be done with newline that use `;` for example, after all related writes are applied.
which is lot better but has some readability changes/trade-offs.

> Please re-submit this as a (tested) PR

Please tag this issue with labels "first good issue", "newbie", or "hacktoberfest" and re-open, which allows other people to submit PR for this trivial change, see reasoning at: https://salsa.debian.org/reproducible-builds/diffoscope/-/issues/210
