### ISSUE TITLE
Valid SSL certificate for travis.debian.net?

### ISSUE THREAD

**Issue by mgedmin** [lamby/travis.debian.net#9]
Given that https://letsencrypt.org is now open to the public, why not set up a valid SSL certificate for https://travis.debian.net?

It would also let you change the .travis.yml to use `wget https://... | sh`, which ought to placate at least some of the "wget | sh is insecure!" crowd.

**Comment by lamby** [comment]
Is this possible whilst remaining on Github?

**Comment by mgedmin** [comment]
I didn't realize.  I also see that you use Fastly.  This makes things more complicated: AFAICS you have to [pay Fastly $$$/month](https://docs.fastly.com/guides/securing-communications/ordering-a-paid-tls-option), if you want to use SSL for a custom domain.

CloudFlare, OTOH, offers SSL even with their [free plan](https://www.cloudflare.com/plans/).  I recently saw someone I follow on Twitter set up a GitHub Pages-backed domain to use SSL by using CloudFlare.  A [guide was mentioned](https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it#using-a-custom-domain-with-cloudflare) in the thread, but apparently you cannot get end-to-end encryption this way: https://github.com/isaacs/github/issues/156

**Comment by lamby** [comment]
> I also see that you use Fastly

I do? :)

**Comment by mgedmin** [comment]
```
$ host travis.debian.net
travis.debian.net is an alias for lamby.github.io.
lamby.github.io is an alias for github.map.fastly.net.
github.map.fastly.net has address 185.31.17.133
```

Ah, GitHub Pages must be using Fastly under the hood.  Now I know what the [mysterious CDN is that doesn't support SSL](https://github.com/isaacs/github/issues/156#issuecomment-75738734) and is blocking GitHub Pages SSL support ;)

**Comment by lamby** [comment]
Ah, well, little I can do in that case... Thanks for investingating. :)
